import = [
	"~/.config/alacritty/gruvbox_dark.toml"
]

[window]
padding = { x = 8, y = 8 }
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 12

[mouse]
hide_when_typing = true

