import = [
	"~/.config/alacritty/gruvbox_dark.toml"
]

[window]
padding = { x = 8 }
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14

[mouse]
hide_when_typing = true

