# Config for sway
#
# Read `man 5 sway` for a complete reference.

### Variables
set $term alacritty
set $browser firefox
set $explorer thunar

### Output configuration
output "HDMI-A-1" {
  scale 1.25
  transform normal
}

### Input configuration
input type:keyboard {
    xkb_layout us,no
    xkb_options grp:shifts_toggle 
}
# You can also configure each device individually.
# Read `man 5 sway-input` for more information about this section.

### Key bindings
#
# Basics:
#
unbindsym $mod+Return
bindsym $mod+Return exec $term
bindsym $mod+Shift+b exec $browser
bindsym $mod+Shift+f exec thunar
bindsym $mod+Ctrl+b exec gtk-launch bluetui
bindsym $mod+Ctrl+d exec gtk-launch lazydocker
bindsym $mod+Ctrl+t exec gtk-launch btop
bindsym $mod+Ctrl+s exec gtk-launch lazyssh

bindsym XF86ScreenSaver exec swaylock -f -c 000000
bindsym $mod+Escape exec swaylock -f -c 000000

mode "special" {
    bindsym s exec slurp | grim -g - - | wl-copy, mode "default"
    bindsym Shift+s exec grim - | wl-copy, mode "default"

    bindsym Ctrl+s exec slurp | grim -g $HOME/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png, mode "default"
    bindsym Ctrl+Shift+s exec grim $HOME/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png, mode "default"

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+z mode "special"

