#!/zsh

export ANDROID_HOME=$HOME/Library/Android/sdk

export PATH=/opt/homebrew/bin:$PATH
export PATH=$HOME/.dotfiles/bin:$PATH
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulators


if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

export EDITOR="nvim"

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

if command -v starship > /dev/null; then
    eval "$(starship init zsh)"
fi

alias vim=nvim
alias setup_mac=$HOME/.dotfiles/setup/macos_setup.sh

if command -v python3.11 > /dev/null; then alias python=python3.11; fi
