#!/bin/zsh

PATH=$PATH:/opt/homebrew/bin
PATH=$PATH:~/.dotnet/tools
PATH=$PATH:~/dotfiles/mac-home/bin

export XDG_CONFIG_HOME="$HOME/.config"

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_REDUCE_BLANKS

alias cat=bat
alias ls=eza
alias vim=nvim
alias n=nvim

autoload -Uz compinit && compinit

source <(fzf --zsh)
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(starship init zsh)"
eval "$(mise activate zsh)"

