#!/bin/zsh

PATH=$PATH:/opt/homebrew/bin
PATH=$PATH:~/.dotnet/tools
PATH=$PATH:~/dotfiles/mac-home/bin

export EDITOR="nvim"
export XDG_CONFIG_HOME="$HOME/.config"
export LC_CTYPE="C.UTF-8" 
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
export SOPS_AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt"
setopt SHARE_HISTORY
setopt HIST_REDUCE_BLANKS
setopt APPEND_HISTORY SHARE_HISTORY INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_REDUCE_BLANKS

alias cat=bat
alias ls=eza
alias vim=nvim
alias n=nvim
alias k=kubectl

setopt AUTO_CD
setopt INTERACTIVE_COMMENTS
setopt NO_BEEP
bindkey -e

tmux_sessionizer_widget() {
  zle -I
  ~/Projects/dotfiles/bin/tmux-sessionizer.sh
  zle redisplay
}
zle -N tmux_sessionizer_widget
bindkey '^F' tmux_sessionizer_widget

autoload -Uz compinit && compinit
zstyle ':completion:*' menu select

export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
source <(fzf --zsh)
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(starship init zsh)"
eval "$(mise activate zsh)"
